### ISSUE TITLE
Pages edit button results in a 404

### ISSUE THREAD

**Issue by RCheesley** [paulhibbitts/demo-grav-learn2-git-sync#1]
Quick note to let you know that the edit button on https://demo.hibbittsdesign.org/grav-learn2-git-sync/intermediate/overview landed me on a 404 - found the page eventually by browsing the repo :)

**Comment by paulhibbitts** [comment]
Thanks so much for the heads-up @RCheesley ! Looks like when updating the site I accidentally copied a symlink to that location (there should not have been an 'overview' page in the 'intermediate' section). I've removed the page.

**Comment by RCheesley** [comment]
No probs - I have been referring to it for ages as we use the markup in our docs for Mautic and it was a really useful guide! Just finally brought the examples over into our docs - hence rummaging on Github to find the markdown to save time!
